name: CI
on: [push]
jobs:
  validate-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        id: go
        with:
          go-version: "^1.19.5"
      - uses: actions/checkout@v3
      - run: go install github.com/ellisonleao/vl/cmd/vl@latest
      - run: vl -a 503,403 -t 30s -w poly.pizza,horde3d.org,p1.untergrund.net,bfxr.net,tigsource.com,gamesounds.xyz,jpct.net README.md
