---

name: CI
on: [push]

jobs:
  validate-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3.2.0
        id: go
        with:
          go-version: "^1.18.2"

      - uses: actions/checkout@v3.0.2

      - run: go install github.com/ellisonleao/vl/cmd/vl@latest
      - run: vl -a 503,403 -t 30s -w horde3d.org,p1.untergrund.net,bfxr.net README.md
